# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password and run app
      uses: appleboy/ssh-action@v1.2.0
      with:
          host: ${{ secrets.SSH_HOST }}
          username: dedulyx
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd gptBot/gptBot/ && docker build -t gptbot . && docker run -e TOKEN=${{secrets.TOKEN}} -e KEY=${{secrets.APIKEY}} -d gptbotv1
      
